/*
 * Gatekeep detection engine — JavaScript port for the static demo page.
 *
 * Ported 1:1 from the Python engine (src/gatekeep/detectors/secrets.py,
 * detectors/pii.py, detectors/normalize.py, detectors/injection.py,
 * policy.py, router.py). The policies.yaml values are inlined in POLICIES
 * below; policies.yaml stays the source of truth.
 *
 * Parity is enforced by demo/parity.test.js, which replays the full harness
 * corpus through this port and compares every action, redaction, finding
 * span, preview, and sha256 against the Python engine's dump
 * (demo/expected.json, regenerated by demo/dump_expected.py).
 *
 * Spans are UTF-16 offsets (Python uses code points) — identical for the
 * ASCII corpus and any realistic secret/PII input.
 */
(function (root, factory) {
  if (typeof module === "object" && module.exports) module.exports = factory();
  else root.Gatekeep = factory();
})(typeof self !== "undefined" ? self : this, function () {
  "use strict";

  // ---- policies.yaml, inlined -------------------------------------------
  const POLICIES = {
    version: 1,
    onParseFailure: "block",
    entropy: { minLength: 20, threshold: 4.0 },
    injection: {
      enabled: true,
      mode: "shadow", // shadow = log-and-allow (default) | enforce = block at threshold
      blockThreshold: 0.8,
      judgeEnabled: false, // Tier-2 seam — inert in v1 (PLAN-injection.md §16)
      judgeBand: [0.3, 0.7],
    },
    rules: [
      { category: "secret", action: "block" },
      { category: "pii", action: "redact" },
      { category: "injection", action: "block" }, // consulted only in enforce mode at/above blockThreshold
    ],
    defaultAction: "allow",
    routing: [{ when: "redact", model: "claude-haiku-4-5-20251001" }],
  };

  const SCAN_CAP = 200000;

  function makePreview(match) {
    return match.slice(0, 4) + "…";
  }

  // ---- detectors/secrets.py ---------------------------------------------
  const SECRET_PATTERNS = [
    ["aws_access_key", /AKIA[0-9A-Z]{16}/g],
    ["github_token", /gh[pousr]_[A-Za-z0-9]{36,}/g],
    ["slack_token", /xox[baprs]-[A-Za-z0-9-]{10,}/g],
    ["private_key", /-----BEGIN( RSA| EC| OPENSSH)? PRIVATE KEY-----/g],
    ["jwt", /eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+/g],
  ];

  const TOKEN_RE = /[A-Za-z0-9+\/=_\-]{20,}/g;
  const HAS_ALPHA = /[A-Za-z]/;
  const HAS_DIGIT = /[0-9]/;

  function shannonEntropy(s) {
    if (!s) return 0.0;
    const chars = Array.from(s);
    const n = chars.length;
    const counts = new Map();
    for (const ch of chars) counts.set(ch, (counts.get(ch) || 0) + 1);
    let h = 0;
    for (const c of counts.values()) h -= (c / n) * Math.log2(c / n);
    return h;
  }

  function scanSecrets(text, entropyMinLength, entropyThreshold) {
    if (entropyMinLength === undefined) entropyMinLength = 20;
    if (entropyThreshold === undefined) entropyThreshold = 4.0;
    const findings = [];
    for (const [name, pattern] of SECRET_PATTERNS) {
      for (const m of text.matchAll(pattern)) {
        findings.push({
          category: "secret",
          detector: name,
          span: [m.index, m.index + m[0].length],
          preview: makePreview(m[0]),
          score: 1.0,
        });
      }
    }

    // Entropy fallback: skip anything already covered by a named regex above.
    const taken = findings.map((f) => f.span);
    for (const m of text.matchAll(TOKEN_RE)) {
      const token = m[0];
      if (token.length < entropyMinLength) continue;
      const start = m.index;
      const end = m.index + token.length;
      if (taken.some(([ts, te]) => start < te && end > ts)) continue;
      // Mixed charset: pure-alpha words and pure-digit runs are never entropy secrets.
      if (!(HAS_ALPHA.test(token) && HAS_DIGIT.test(token))) continue;
      if (shannonEntropy(token) >= entropyThreshold) {
        findings.push({
          category: "secret",
          detector: "entropy",
          span: [start, end],
          preview: makePreview(token),
          score: 1.0,
        });
      }
    }
    return findings;
  }

  // ---- detectors/pii.py ---------------------------------------------------
  const SSN_RE = /\b(\d{3})-(\d{2})-(\d{4})\b/g;
  const CC_RUN_RE = /(?<!\d)\d{13,19}(?!\d)/g;
  const EMAIL_RE = /\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b/g;
  const PHONE_RE = /(?<!\d)(?:\+1[-. ]?)?(?:\(\d{3}\)\s?|\d{3}[-. ])\d{3}[-. ]\d{4}(?!\d)/g;

  function luhnCheck(digits) {
    let total = 0;
    const rev = digits.split("").reverse();
    for (let i = 0; i < rev.length; i++) {
      let d = parseInt(rev[i], 10);
      if (i % 2 === 1) {
        d *= 2;
        if (d > 9) d -= 9;
      }
      total += d;
    }
    return total % 10 === 0;
  }

  function ssnValid(area, group, serial) {
    // SSA never issues: area 000/666/900-999, group 00, serial 0000.
    if (area === "000" || area === "666" || area.startsWith("9")) return false;
    return group !== "00" && serial !== "0000";
  }

  function scanPII(text) {
    const findings = [];
    for (const m of text.matchAll(SSN_RE)) {
      if (ssnValid(m[1], m[2], m[3])) {
        findings.push({
          category: "pii",
          detector: "ssn",
          span: [m.index, m.index + m[0].length],
          preview: makePreview(m[0]),
          score: 1.0,
        });
      }
    }
    for (const m of text.matchAll(CC_RUN_RE)) {
      if (luhnCheck(m[0])) {
        findings.push({
          category: "pii",
          detector: "credit_card",
          span: [m.index, m.index + m[0].length],
          preview: makePreview(m[0]),
          score: 1.0,
        });
      }
    }
    for (const m of text.matchAll(EMAIL_RE)) {
      findings.push({
        category: "pii",
        detector: "email",
        span: [m.index, m.index + m[0].length],
        preview: makePreview(m[0]),
        score: 1.0,
      });
    }
    for (const m of text.matchAll(PHONE_RE)) {
      findings.push({
        category: "pii",
        detector: "phone",
        span: [m.index, m.index + m[0].length],
        preview: makePreview(m[0]),
        score: 1.0,
      });
    }
    return findings;
  }

  // ---- detectors/normalize.py ---------------------------------------------
  // Zero-width and direction-control characters attackers lace into trigger words.
  const ZERO_WIDTH = new Set([
    "​", "‌", "‍", "‎", "‏", // ZWSP / ZWNJ / ZWJ / LRM / RLM
    "‪", "‫", "‬", "‭", "‮", // directional embedding/override
    "⁠", "﻿",                               // word joiner, BOM / ZWNBSP
  ]);

  // Small documented map of common Cyrillic/Greek Latin-lookalikes. Not exhaustive.
  const HOMOGLYPHS = {
    // Cyrillic lowercase
    "а": "a", "е": "e", "о": "o", "р": "p", "с": "c",
    "у": "y", "х": "x", "і": "i", "ѕ": "s", "ј": "j",
    // Cyrillic uppercase
    "А": "A", "В": "B", "Е": "E", "К": "K", "М": "M",
    "Н": "H", "О": "O", "Р": "P", "С": "C", "Т": "T",
    "Х": "X", "І": "I", "Ѕ": "S", "Ј": "J",
    // Greek lowercase
    "α": "a", "ε": "e", "ι": "i", "κ": "k", "ν": "v",
    "ο": "o", "ρ": "p", "τ": "t", "υ": "u", "χ": "x",
    // Greek uppercase
    "Α": "A", "Β": "B", "Ε": "E", "Ζ": "Z", "Η": "H",
    "Ι": "I", "Κ": "K", "Μ": "M", "Ν": "N", "Ο": "O",
    "Ρ": "P", "Τ": "T", "Υ": "Y", "Χ": "X",
  };

  function normalize(text) {
    // Returns { text, obfuscationPresent } — NFKC, strip zero-width, fold homoglyphs,
    // collapse whitespace. Plain NFD→NFC composition does NOT trip the flag.
    const nfkc = text.normalize("NFKC");
    const compatChanged = nfkc !== text.normalize("NFC");

    let withoutZw = "";
    for (const c of nfkc) if (!ZERO_WIDTH.has(c)) withoutZw += c;
    const zwFound = withoutZw.length !== nfkc.length;

    let folded = "";
    for (const c of withoutZw) folded += HOMOGLYPHS[c] || c;
    const foldFound = folded !== withoutZw;

    const collapsed = folded.replace(/\s+/g, " ").trim();
    return { text: collapsed, obfuscationPresent: !!(compatChanged || zwFound || foldFound) };
  }

  // ---- detectors/injection.py ---------------------------------------------
  // Structure-keyed patterns (verb + object shape, never bare trigger words),
  // ported 1:1. Spans reference NORMALIZED-text offsets, exactly like Python.
  const _NOUNS = "(?:instructions?|prompts?|rules?|directives?|guidelines?|constraints?|commands?|context|programming|training)";
  const _LEAK_VERBS = "(?:print|show|reveal|repeat|output|display|disclose|leak|expose|share|tell\\s+me|give\\s+me|recite|dump|paste)";
  const _EXFIL_VERBS = "(?:send|forward|post|upload|email|exfiltrate|transmit|leak|submit)";
  const _EXFIL_PAYLOAD =
    "(?:conversation|chat\\s+history|message\\s+history|(?:this|the|our)\\s+(?:chat|conversation|thread|context)" +
    "|secrets?|credentials?|api\\s+keys?|passwords?|tokens?|everything\\s+above|the\\s+above)";

  // technique -> [[regex, weight]]
  const INJECTION_PATTERNS = {
    instruction_override: [
      [new RegExp(
        "\\b(?:ignore|disregard|forget|override|bypass|discard|drop)\\b[^.?!\\n]{0,40}" +
        "\\b(?:previous|prior|above|earlier|preceding|initial|original|all|any|your|these|those|system|the)\\b" +
        "[^.?!\\n]{0,40}\\b" + _NOUNS + "\\b", "gi"), 0.85],
      [new RegExp("\\b(?:ignore|disregard|forget)\\b[^.?!\\n]{0,20}\\babove\\b[^.?!\\n]{0,20}\\b(?:and|instead)\\b", "gi"), 0.85],
      [new RegExp("\\bnew\\s+(?:instructions?|rules?|directives?)\\s*:", "gi"), 0.8],
      // Reset idiom: "forget everything we discussed", "disregard all that came before".
      [new RegExp(
        "\\b(?:forget|disregard|ignore)\\s+(?:about\\s+)?(?:everything|all)\\b[^.?!\\n]{0,40}" +
        "\\b(?:before|above|previous|prior|so\\s+far|earlier|that\\s+(?:came|was)\\s+before" +
        "|we(?:'ve|\\s+have)?\\s+(?:just\\s+)?(?:talked|discussed|said|covered))\\b", "gi"), 0.85],
      [new RegExp(
        "\\b(?:do\\s+not|don'?t|stop|refuse\\s+to)\\s+(?:follow(?:ing)?|obey(?:ing)?|listen\\s+to|comply\\s+with)\\b" +
        "[^.?!\\n]{0,40}\\b(?:instructions?|rules?|guidelines?|directives?|commands?|orders?|programming" +
        "|system|above|previous|original)\\b", "gi"), 0.8],
      // German coverage: deepset/prompt-injections carries German attack rows.
      [new RegExp(
        "\\b(?:ignorier\\w*|vergiss|vergesse?n?)\\b[^.?!\\n]{0,50}" +
        "\\b(?:alles|anweisung\\w*|instruktion\\w*|vorherig\\w*|obig\\w*|regeln)\\b", "gi"), 0.85],
    ],
    role_manipulation: [
      // Persona/capability reassignment — structure-keyed so "you are now logged in" is spared.
      [new RegExp(
        "\\byou\\s+are\\s+now\\s+(?:a\\s+|an\\s+|the\\s+)?(?:[a-z]+\\s+){0,3}?" +
        "(?:ai|assistant|bot|model|chatbot|dan|hacker|persona|character|entity" +
        "|unrestricted|unfiltered|uncensored|jailbroken)\\b", "gi"), 0.8],
      [new RegExp(
        "\\byou\\s+are\\s+no\\s+longer\\s+(?:bound|restricted|limited|required|obligated|constrained" +
        "|subject\\s+to|claude|an?\\s+ai)\\b", "gi"), 0.8],
      [new RegExp("\\bfrom\\s+now\\s+on\\b[^.?!\\n]{0,60}\\b(?:you\\s+(?:are|will|must|can|should)|you'?re)\\b", "gi"), 0.8],
      [new RegExp(
        "\\b(?:act|pretend|behave|roleplay)\\b[^.?!\\n]{0,30}\\b(?:as\\s+if|as\\s+though|like|as)\\b[^.?!\\n]{0,50}" +
        "\\b(?:no\\s+(?:rules|restrictions?|limitations?|filters?|guidelines?)|unrestricted|unfiltered|uncensored" +
        "|jailbro\\w+|DAN|evil|without\\s+(?:any\\s+)?(?:rules|restrictions?|limitations?|filters?|ethic\\w*))", "gi"), 0.85],
      [new RegExp("\\b(?:DAN\\s+mode|jailbreak|jailbroken)\\b", "gi"), 0.8],
      // "developer/god mode" only when being activated or declared on — spares "Chrome's developer mode".
      [new RegExp(
        "\\b(?:enter|enable|activ\\w+|turn\\s+on|switch\\s+(?:to|into)|go\\s+into|unlock)\\b" +
        "[^.?!\\n]{0,20}\\b(?:developer|god|dan)\\s+mode\\b", "gi"), 0.8],
      [new RegExp("\\b(?:developer|god|dan)\\s+mode\\s+(?:enabled|activated|unlocked|is\\s+(?:now\\s+)?on)\\b", "gi"), 0.8],
      // "no ethical guidelines", "without safety and content filters"
      [new RegExp(
        "\\b(?:no|without|free\\s+(?:of|from))\\s+(?:(?:ethical|moral|safety|content)\\b[\\s,]+(?:or\\s+|and\\s+)?){1,3}" +
        "(?:guidelines?|restrictions?|filters?|constraints?|policies|rules?)\\b", "gi"), 0.8],
    ],
    system_prompt_leak: [
      [new RegExp(
        "\\b" + _LEAK_VERBS + "\\b[^.?!\\n]{0,40}" +
        "\\b(?:system\\s+prompt|system\\s+message|initial\\s+(?:prompt|instructions?)" +
        "|hidden\\s+(?:prompt|instructions?)|pre.?prompt|original\\s+instructions?)\\b", "gi"), 0.85],
      [new RegExp(
        "\\b" + _LEAK_VERBS + "\\b[^.?!\\n]{0,30}" +
        "\\byour\\s+(?:instructions?|prompt|rules|guidelines|directives|configuration|programming)\\b", "gi"), 0.8],
      [new RegExp(
        "\\bwhat\\s+(?:is|are|was|were)\\s+(?:your|the)\\s+" +
        "(?:system\\s+prompt|initial\\s+instructions?|hidden\\s+instructions?|original\\s+prompt)\\b", "gi"), 0.8],
      // "print the above prompt" (deepset END-marker idiom).
      [new RegExp(
        "\\b(?:print|repeat|output|display|reproduce)\\b[^.?!\\n]{0,25}" +
        "\\b(?:the\\s+)?above\\s+(?:prompt|instructions?|input|system\\s+prompt)\\b", "gi"), 0.8],
    ],
    delimiter_injection: [
      [new RegExp("</?\\s*(?:system|sys|assistant|instructions?|admin)\\s*>", "gi"), 0.8],
      [new RegExp("\\[\\s*/?\\s*(?:SYSTEM|INST|ADMIN)\\s*\\]", "gi"), 0.8],
      [new RegExp("<\\|\\s*(?:im_start|im_end|system|user|assistant|endoftext)\\s*\\|?>", "gi"), 0.8],
      [new RegExp("<<\\s*/?\\s*SYS\\s*>>", "gi"), 0.8],
      [new RegExp("(?:^|\\s)(?:#{2,}|={3,}|-{3,})\\s*(?:system|admin|new\\s+instructions?)\\b", "gi"), 0.75],
      [new RegExp("\\bBEGIN\\s+(?:SYSTEM|ADMIN|NEW)\\s+(?:PROMPT|INSTRUCTIONS?|MESSAGE)\\b", "gi"), 0.8],
    ],
    exfiltration: [
      [new RegExp(
        "\\b" + _EXFIL_VERBS + "\\b[^.?!\\n]{0,60}\\b" + _EXFIL_PAYLOAD + "\\b[^.?!\\n]{0,80}\\b(?:to|at)\\b", "gi"), 0.8],
      [new RegExp(
        "\\b" + _EXFIL_VERBS + "\\b[^.?!\\n]{0,80}\\bto\\s+(?:https?://\\S+|[\\w.+-]+@[\\w-]+(?:\\.[\\w-]+)+)", "gi"), 0.75],
      // Markdown image with a query string: the classic zero-click exfil channel.
      [new RegExp("!\\[[^\\]]{0,80}\\]\\(\\s*https?://[^)\\s]{1,200}[?&=][^)\\s]*\\)", "gi"), 0.8],
    ],
  };

  const OBFUSCATION_WEIGHT = 0.4;

  function scanInjection(text) {
    const norm = normalize(text);
    const findings = [];
    for (const technique of Object.keys(INJECTION_PATTERNS)) {
      for (const [rx, weight] of INJECTION_PATTERNS[technique]) {
        for (const m of norm.text.matchAll(rx)) {
          findings.push({
            category: "injection",
            detector: technique,
            span: [m.index, m.index + m[0].length],
            preview: makePreview(m[0]),
            score: weight,
          });
        }
      }
    }
    if (norm.obfuscationPresent) {
      findings.push({
        category: "injection",
        detector: "obfuscation",
        span: [0, norm.text.length],
        preview: "…",
        score: OBFUSCATION_WEIGHT,
      });
    }
    return findings;
  }

  // Aggregate injection findings to one document score: 1 - Π(1 - w_i), capped at 1.0.
  function documentScore(findings) {
    let p = 1.0;
    for (const f of findings) {
      if (f.category === "injection") p *= 1.0 - Math.min(f.score, 1.0);
    }
    return Math.min(1.0, 1.0 - p);
  }

  // ---- detectors/__init__.py run_all (Presidio layer not ported: optional,
  // off by default, and needs a Python NLP runtime) ------------------------
  function runAll(text, policies) {
    const cfg = policies || POLICIES;
    let findings = scanSecrets(text, cfg.entropy.minLength, cfg.entropy.threshold);
    findings = findings.concat(scanPII(text));
    if (cfg.injection && cfg.injection.enabled) findings = findings.concat(scanInjection(text));
    return findings;
  }

  // ---- policy.py -----------------------------------------------------------
  const SEVERITY = { allow: 0, redact: 1, block: 2 };

  function actionFor(finding, policies) {
    for (const rule of policies.rules) {
      if (rule.category === finding.category) return rule.action; // first match wins
    }
    return policies.defaultAction;
  }

  function redactText(text, findings, policies) {
    // Replace redact-mapped finding spans right-to-left so earlier offsets stay valid.
    const ordered = findings.slice().sort((a, b) => b.span[0] - a.span[0]);
    for (const f of ordered) {
      if (actionFor(f, policies) === "redact") {
        const [start, end] = f.span;
        text = text.slice(0, start) + "[REDACTED:" + f.category.toUpperCase() + "]" + text.slice(end);
      }
    }
    return text;
  }

  function decide(texts, findingsPerText, policies) {
    let action = "allow";
    const matched = [];

    // Injection findings are handled out of band: scored + mode-aware, and kept away
    // from redaction (their spans are normalized-text offsets — see scanInjection).
    const basePerText = findingsPerText.map((fs) => fs.filter((f) => f.category !== "injection"));
    const injectionFindings = [];
    for (const fs of findingsPerText) {
      for (const f of fs) if (f.category === "injection") injectionFindings.push(f);
    }

    for (const findings of basePerText) {
      for (const f of findings) {
        const fa = actionFor(f, policies);
        matched.push(f.category + ":" + fa);
        if (SEVERITY[fa] > SEVERITY[action]) action = fa;
      }
    }

    let injectionScore = 0.0;
    for (const f of injectionFindings) injectionScore = Math.max(injectionScore, f.score);
    const injectionCategories = [...new Set(injectionFindings.map((f) => f.detector))].sort();
    if (injectionFindings.length) {
      const cfg = policies.injection;
      if (cfg.mode === "enforce" && injectionScore >= cfg.blockThreshold) {
        const fa = actionFor(injectionFindings[0], policies); // the policies.yaml injection rule
        matched.push("injection:" + fa);
        if (SEVERITY[fa] > SEVERITY[action]) action = fa;
      } else {
        matched.push("injection:shadow"); // shadow / below threshold: log-and-allow
      }
    }

    let redacted = texts.slice();
    if (action === "redact") {
      redacted = texts.map((t, i) => redactText(t, basePerText[i], policies));
    }
    return {
      action: action,
      redactedTexts: redacted,
      matchedRules: matched,
      injectionScore: injectionScore,
      injectionCategories: injectionCategories,
    };
  }

  // UI helper: the redacted text as segments so redactions can be highlighted.
  // Overlapping redact spans (never produced by the current detectors) keep the
  // rightmost finding, matching the right-to-left replacement above.
  function redactSegments(text, findings, policies) {
    const kept = [];
    const ordered = findings
      .filter((f) => actionFor(f, policies) === "redact")
      .sort((a, b) => b.span[0] - a.span[0]);
    for (const f of ordered) {
      if (!kept.some((k) => f.span[0] < k.span[1] && f.span[1] > k.span[0])) kept.push(f);
    }
    kept.sort((a, b) => a.span[0] - b.span[0]);
    const segments = [];
    let cursor = 0;
    for (const f of kept) {
      if (f.span[0] > cursor) segments.push({ type: "text", value: text.slice(cursor, f.span[0]) });
      segments.push({
        type: "redaction",
        value: "[REDACTED:" + f.category.toUpperCase() + "]",
        detector: f.detector,
        preview: f.preview,
      });
      cursor = f.span[1];
    }
    if (cursor < text.length) segments.push({ type: "text", value: text.slice(cursor) });
    return segments;
  }

  // ---- router.py -----------------------------------------------------------
  function routeModel(requested, decision, policies) {
    for (const rule of policies.routing) {
      if (rule.when === decision.action) return rule.model; // first match wins
    }
    return requested;
  }

  // ---- sha256 (pure JS so the page works on file:// too; verified against
  // node:crypto and Python hashlib by parity.test.js) -----------------------
  const K = [
    0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
    0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
    0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
    0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
    0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
    0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
    0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
    0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
  ];

  function rotr(x, n) {
    return ((x >>> n) | (x << (32 - n))) >>> 0;
  }

  function sha256Hex(message) {
    const msg = new TextEncoder().encode(message);
    const bitLenLo = (msg.length << 3) >>> 0;
    const bitLenHi = Math.floor((msg.length * 8) / 4294967296);
    const padded = new Uint8Array(Math.ceil((msg.length + 9) / 64) * 64);
    padded.set(msg);
    padded[msg.length] = 0x80;
    const dv = new DataView(padded.buffer);
    dv.setUint32(padded.length - 8, bitLenHi);
    dv.setUint32(padded.length - 4, bitLenLo);

    let H = [0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19];
    const w = new Uint32Array(64);
    for (let i = 0; i < padded.length; i += 64) {
      for (let t = 0; t < 16; t++) w[t] = dv.getUint32(i + t * 4);
      for (let t = 16; t < 64; t++) {
        const s0 = rotr(w[t - 15], 7) ^ rotr(w[t - 15], 18) ^ (w[t - 15] >>> 3);
        const s1 = rotr(w[t - 2], 17) ^ rotr(w[t - 2], 19) ^ (w[t - 2] >>> 10);
        w[t] = (w[t - 16] + s0 + w[t - 7] + s1) >>> 0;
      }
      let a = H[0], b = H[1], c = H[2], d = H[3], e = H[4], f = H[5], g = H[6], h = H[7];
      for (let t = 0; t < 64; t++) {
        const S1 = rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25);
        const ch = (e & f) ^ (~e & g);
        const t1 = (h + S1 + ch + K[t] + w[t]) >>> 0;
        const S0 = rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22);
        const maj = (a & b) ^ (a & c) ^ (b & c);
        const t2 = (S0 + maj) >>> 0;
        h = g; g = f; f = e; e = (d + t1) >>> 0;
        d = c; c = b; b = a; a = (t1 + t2) >>> 0;
      }
      H = [
        (H[0] + a) >>> 0, (H[1] + b) >>> 0, (H[2] + c) >>> 0, (H[3] + d) >>> 0,
        (H[4] + e) >>> 0, (H[5] + f) >>> 0, (H[6] + g) >>> 0, (H[7] + h) >>> 0,
      ];
    }
    return H.map((x) => x.toString(16).padStart(8, "0")).join("");
  }

  return {
    POLICIES: POLICIES,
    SCAN_CAP: SCAN_CAP,
    SECRET_PATTERNS: SECRET_PATTERNS,
    makePreview: makePreview,
    shannonEntropy: shannonEntropy,
    scanSecrets: scanSecrets,
    luhnCheck: luhnCheck,
    ssnValid: ssnValid,
    scanPII: scanPII,
    normalize: normalize,
    scanInjection: scanInjection,
    documentScore: documentScore,
    runAll: runAll,
    actionFor: actionFor,
    decide: decide,
    redactSegments: redactSegments,
    routeModel: routeModel,
    sha256Hex: sha256Hex,
  };
});
